#!/usr/bin/python

import socket

server = 'srvr41.engin.umich.edu'
port = 1680
down_interval = 900

def request(req):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect ((server, port))
    sock.sendall(req)
    data = sock.recv(50000)
    while 1:
        buff = sock.recv(50000)
        if len(buff):
            data = data + buff
        else:
            break
    sock.close()
    return data



print '=' * 80
print 'Netuse Administration Command Line Interface'
print '=' * 80

while 1:
    print
    command = raw_input('NUADMIN> ')
